// Code generated by openapi-gen; DO NOT EDIT.
//
// The `bb-bastion` plugin API's "plumbing" layer: the generated clients, plus a
// container that groups them behind one transport. Everything here returns the
// response envelope exactly as the OpenAPI specification describes it.
import { HealthApi } from "./api/health.gen.js";
import { SandboxesApi } from "./api/sandboxes.gen.js";
import { TemplateApi } from "./api/template.gen.js";

import type { Transport } from "./transport.js";

/**
 * The porcelain layer in `@unikraft/cloud` derives the URL. Use this class
 * only when you want the raw envelopes against an instance you already have.
 *
 * @example
 * import { ApiClient } from "@unikraft/cloud/core/http";
 * import { BbBastionPluginApi } from "@unikraft/cloud-plugin-bb-bastion-api";
 *
 * const api = new BbBastionPluginApi(
 *   new ApiClient({
 *     baseUrl: `https://api.fra.unikraft.cloud/v1/instances/${uuid}/plugins/bb-bastion`,
 *     token: process.env.UKC_TOKEN,
 *   }),
 * );
 */
export class BbBastionPluginApi {
  /** The `Health` resource of this plugin. */
  readonly health: HealthApi;
  /** The `Sandboxes` resource of this plugin. */
  readonly sandboxes: SandboxesApi;
  /** The `Template` resource of this plugin. */
  readonly template: TemplateApi;

  constructor(transport: Transport) {
    for (const method of ["request", "bytes", "stream"] as const) {
      if (typeof transport[method] !== "function") {
        throw new TypeError(
          `The transport has no ${method}() method. Pass an ApiClient from @unikraft/cloud/core/http, or an object with request(), bytes() and stream().`,
        );
      }
    }
    this.health = new HealthApi(transport);
    this.sandboxes = new SandboxesApi(transport);
    this.template = new TemplateApi(transport);
  }
}

export * from "./api/index.gen.js";
export type { CallOptions, RequestArgs, Transport } from "./transport.js";
