// Code generated by openapi-gen; DO NOT EDIT.
//
// The contract between this package and the transport that carries its
// requests. `ApiClient` in `@unikraft/cloud/core/http` implements it, and any
// object with these three methods satisfies it, because the type is structural.
// This file imports nothing, so the package needs no dependency on the SDK.
//
// This is the only copy of the interface. The SDK's `ApiClient` satisfies it by
// shape, and the SDK's test suite checks that against the published plugin
// package. Widening is safe: a new optional parameter, a wider input type. A
// rename, a new required parameter, or a changed return type must reach
// `ApiClient` in the SDK as well, and every plugin package must be republished.

/** A value that can be serialised into a query string. */
export type QueryValue =
  | string
  | number
  | boolean
  | Array<string | number | boolean>
  | undefined
  | null;

/** Per-call options accepted by every generated operation. */
export interface CallOptions {
  /** Abort the request via an `AbortSignal`. */
  signal?: AbortSignal;
  /** Extra headers merged over the client defaults for this call only. */
  headers?: Record<string, string>;
  /** Override the base URL (e.g. to target a different metro) for this call. */
  baseUrl?: string;
}

/** The shape of one request, as a generated operation hands it to the transport. */
export interface RequestArgs {
  method: string;
  path: string;
  query?: Record<string, QueryValue>;
  body?: unknown;
}

/**
 * What a generated class needs from the SDK: one method per response shape.
 */
export interface Transport {
  /** Perform a request and return the parsed JSON envelope typed as `T`. */
  request<T>(args: RequestArgs, options?: CallOptions): Promise<T>;
  /** Perform a request whose response is a raw byte body and return it verbatim. */
  bytes(args: RequestArgs, options?: CallOptions): Promise<Uint8Array>;
  /** Perform a request whose response is a `text/event-stream` and yield each event's payload. */
  stream<T>(args: RequestArgs, options?: CallOptions): AsyncGenerator<T, void, void>;
}
