// Code generated by openapi-gen; DO NOT EDIT.
import type * as models from "./models.gen.js";
import type { CallOptions, Transport } from "../transport.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Health` resource. Methods return the raw response envelope.
 */
export class HealthApi {
  /** The transport every request of this resource goes through. */
  readonly transport: Transport;

  constructor(transport: Transport) {
    this.transport = transport;
  }

  /**
   * Report readiness, template state and sandbox counts.
   */
  getHealth(
    params: CallOptions = {},
  ): Promise<models.HealthResponse> {
    return this.transport.request<models.HealthResponse>(
      {
        method: "GET",
        path: `/health`,
      },
      params,
    );
  }
}
