// Code generated by openapi-gen; DO NOT EDIT.
//
// Type definitions for the Unikraft Cloud `bb-bastion`
// plugin API, generated from its OpenAPI specification. These mirror the wire
// format exactly.

/**
 * The enrollment bootstrap bb hands a machine provider for a new host.
 */

export interface BootstrapRequest {
  /**
   * Identifier bb assigned to the host.
   */
  "host_id": string;
  /**
   * URL of the bb server the daemon must dial.
   */
  "server_url": string;
  /**
   * Extra HTTP headers the daemon sends on every request to the server.
   */
  "headers"?: Record<string, string>;
  /**
   * One-time enrollment credential.
   */
  "credential": string;
  /**
   * RFC 3339 instant after which the credential is no longer accepted.
   */
  "expires_at": string;
}

/**
 * Standard response envelope wrapping all API responses.
 */

export interface BootstrapSandboxResponse {
  /**
   * The status of the response.
   */
  "status": ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  "message"?: string;
  /**
   * The response data for this request.
   */
  "data"?: BootstrapSandboxResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  "errors"?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  "op_time_us": number;
}

/**
 * Result of enrolling a sandbox's host and launching its daemon.
 */

export interface BootstrapSandboxResponseData {
  "host_id": string;
  /**
   * Process id of the launched daemon.
   */
  "daemon_pid": number;
}

/**
 * Sizing and environment for a new sandbox.
 */

export interface CreateSandboxRequest {
  /**
   * bb thread the sandbox serves; also its identifier.
   */
  "thread_id": string;
  /**
   * vCPUs; the configured default when omitted.
   */
  "vcpus"?: number;
  /**
   * Memory in MiB; the configured default when omitted.
   */
  "memory_mb"?: number;
  /**
   * Environment variables added to the sandbox on top of the configured ones.
   */
  "extra_env"?: Record<string, string>;
  /**
   * Image the sandbox boots from; the configured one when omitted. Another
   * image cannot be cloned from the warm template, so the sandbox is built
   * from the image and takes longer to start.
   */
  "image"?: string;
  /**
   * Ports the sandbox publishes to the Internet, each on the public port of
   * the same number.
   */
  "ports"?: number[];
}

/**
 * Standard response envelope wrapping all API responses.
 */

export interface DeleteAllSandboxesResponse {
  /**
   * The status of the response.
   */
  "status": ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  "message"?: string;
  /**
   * The response data for this request.
   */
  "data"?: DeleteAllSandboxesResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  "errors"?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  "op_time_us": number;
}


export interface DeleteAllSandboxesResponseData {
  /**
   * Identifiers of the sandboxes that were deleted.
   */
  "deleted": string[];
}

/**
 * Standard response envelope wrapping all API responses.
 */

export interface DeleteSandboxResponse {
  /**
   * The status of the response.
   */
  "status": ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  "message"?: string;
  /**
   * The response data for this request.
   */
  "data"?: DeleteSandboxResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  "errors"?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  "op_time_us": number;
}


export interface DeleteSandboxResponseData {
  /**
   * The instance existed and was deleted.
   */
  "deleted": boolean;
}

/**
 * Standard response envelope wrapping all API responses.
 */

export interface HealthResponse {
  /**
   * The status of the response.
   */
  "status": ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  "message"?: string;
  /**
   * The response data for this request.
   */
  "data"?: HealthResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  "errors"?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  "op_time_us": number;
}

/**
 * Bastion readiness and a summary of what it manages.
 */

export interface HealthResponseData {
  /**
   * The bastion accepts sandbox requests.
   */
  "ready": boolean;
  /**
   * Bastion build version.
   */
  "version": string;
  /**
   * Metro the bastion and its sandboxes run in.
   */
  "metro": string;
  "template": TemplateSummary;
  "sandboxes": SandboxCounts;
}

/**
 * Standard response envelope wrapping all API responses.
 */

export interface ListSandboxesResponse {
  /**
   * The status of the response.
   */
  "status": ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  "message"?: string;
  /**
   * The response data for this request.
   */
  "data"?: ListSandboxesResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  "errors"?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  "op_time_us": number;
}


export interface ListSandboxesResponseData {
  "sandboxes": SandboxResponseData[];
}

/**
 * The error response message for an API request.
 */

export interface ResponseError {
  /**
   * The HTTP status code of the error.
   */
  "status": number;
}

/**
 * The response status of an API request.
 */

export type ResponseStatus =
  | "success"
  | "error"
  | "partial_success";

/**
 * Sandbox counts embedded in the health report.
 */

export interface SandboxCounts {
  "total": number;
  "standby": number;
  "running": number;
}

/**
 * Standard response envelope wrapping all API responses.
 */

export interface SandboxResponse {
  /**
   * The status of the response.
   */
  "status": ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  "message"?: string;
  /**
   * The response data for this request.
   */
  "data"?: SandboxResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  "errors"?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  "op_time_us": number;
}

/**
 * A per-thread sandbox instance.
 */

export interface SandboxResponseData {
  /**
   * Sandbox identifier; equal to the bb thread id it serves.
   */
  "id": string;
  /**
   * Instance name on Unikraft Cloud.
   */
  "name": string;
  /**
   * Instance UUID on Unikraft Cloud.
   */
  "instance_uuid": string;
  /**
   * Private FQDN the bastion reaches the instance at.
   */
  "private_fqdn": string;
  /**
   * Public FQDN of the sandbox's service group; absent when it publishes
   * nothing.
   */
  "fqdn"?: string;
  /**
   * Ports the sandbox publishes to the Internet.
   */
  "services"?: SandboxService[];
  "state": SandboxState;
  "vcpus": number;
  "memory_mb": number;
  /**
   * RFC 3339 instant of the last frame seen from the sandbox's daemon.
   */
  "last_activity_at"?: string;
  /**
   * RFC 3339 instant the instance was created.
   */
  "created_at": string;
}

/**
 * A port a sandbox publishes to the Internet.
 */

export interface SandboxService {
  /**
   * Public port, which is also the port the sandbox listens on.
   */
  "port": number;
  /**
   * URL the port is reached at from the Internet.
   */
  "url": string;
}

/**
 * Lifecycle state of a sandbox, derived from its instance.
 */

export type SandboxState =
  | "creating"
  | "running"
  | "standby"
  | "stopped"
  | "deleting";

/**
 * Standard response envelope wrapping all API responses.
 */

export interface TemplateResponse {
  /**
   * The status of the response.
   */
  "status": ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  "message"?: string;
  /**
   * The response data for this request.
   */
  "data"?: TemplateResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  "errors"?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  "op_time_us": number;
}

/**
 * The template new sandboxes are created from.
 */

export interface TemplateResponseData {
  /**
   * Hash of the inputs the template was built from.
   */
  "key": string;
  "state": TemplateState;
  /**
   * UUID of the template instance, once created.
   */
  "instance_uuid"?: string;
  /**
   * RFC 3339 instant the template was created.
   */
  "created_at"?: string;
}

/**
 * Lifecycle state of the sandbox template.
 */

export type TemplateState =
  | "absent"
  | "warming"
  | "ready"
  | "failed";

/**
 * Template summary embedded in the health report.
 */

export interface TemplateSummary {
  /**
   * Hash of the inputs the template was built from.
   */
  "key": string;
  "state": TemplateState;
}


export interface WarmTemplateRequest {
  /**
   * Rebuild the template even when one with the current key is ready.
   */
  "force"?: boolean;
}

/**
 * Standard response envelope wrapping all API responses.
 */

export interface WarmTemplateResponse {
  /**
   * The status of the response.
   */
  "status": ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  "message"?: string;
  /**
   * The response data for this request.
   */
  "data"?: WarmTemplateResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  "errors"?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  "op_time_us": number;
}


export interface WarmTemplateResponseData {
  "key": string;
  "state": TemplateState;
}

