// Code generated by openapi-gen; DO NOT EDIT.
import type * as models from "./models.gen.js";
import type { CallOptions, Transport } from "../transport.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Sandboxes` resource. Methods return the raw response envelope.
 */
export class SandboxesApi {
  /** The transport every request of this resource goes through. */
  readonly transport: Transport;

  constructor(transport: Transport) {
    this.transport = transport;
  }

  /**
   * Forward bb's enrollment bootstrap into the sandbox and start its daemon.
   */
  bootstrapSandbox(
    id: string,
    params: {
      body: models.BootstrapRequest;
    } & CallOptions,
  ): Promise<models.BootstrapSandboxResponse> {
    return this.transport.request<models.BootstrapSandboxResponse>(
      {
        method: "POST",
        path: `/sandboxes/${encodeURIComponent(id)}/bootstrap`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Create the sandbox for a thread, or return it when it already exists.
   */
  createSandbox(
    params: {
      body: models.CreateSandboxRequest;
    } & CallOptions,
  ): Promise<models.SandboxResponse> {
    return this.transport.request<models.SandboxResponse>(
      {
        method: "POST",
        path: `/sandboxes`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete every sandbox.
   */
  deleteAllSandboxes(
    params: CallOptions = {},
  ): Promise<models.DeleteAllSandboxesResponse> {
    return this.transport.request<models.DeleteAllSandboxesResponse>(
      {
        method: "DELETE",
        path: `/sandboxes`,
      },
      params,
    );
  }

  /**
   * Delete one sandbox and its instance.
   */
  deleteSandbox(
    id: string,
    params: CallOptions = {},
  ): Promise<models.DeleteSandboxResponse> {
    return this.transport.request<models.DeleteSandboxResponse>(
      {
        method: "DELETE",
        path: `/sandboxes/${encodeURIComponent(id)}`,
      },
      params,
    );
  }

  /**
   * Describe one sandbox.
   */
  getSandbox(
    id: string,
    params: CallOptions = {},
  ): Promise<models.SandboxResponse> {
    return this.transport.request<models.SandboxResponse>(
      {
        method: "GET",
        path: `/sandboxes/${encodeURIComponent(id)}`,
      },
      params,
    );
  }

  /**
   * List every sandbox the bastion knows about.
   */
  listSandboxes(
    params: CallOptions = {},
  ): Promise<models.ListSandboxesResponse> {
    return this.transport.request<models.ListSandboxesResponse>(
      {
        method: "GET",
        path: `/sandboxes`,
      },
      params,
    );
  }
}
