// Code generated by openapi-gen; DO NOT EDIT.
import type * as models from "./models.gen.js";
import type { CallOptions, Transport } from "../transport.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Template` resource. Methods return the raw response envelope.
 */
export class TemplateApi {
  /** The transport every request of this resource goes through. */
  readonly transport: Transport;

  constructor(transport: Transport) {
    this.transport = transport;
  }

  /**
   * Describe the current template.
   */
  getTemplate(
    params: CallOptions = {},
  ): Promise<models.TemplateResponse> {
    return this.transport.request<models.TemplateResponse>(
      {
        method: "GET",
        path: `/template`,
      },
      params,
    );
  }

  /**
   * Build the template ahead of the first sandbox.
   */
  warmTemplate(
    params: {
      body: models.WarmTemplateRequest;
    } & CallOptions,
  ): Promise<models.WarmTemplateResponse> {
    return this.transport.request<models.WarmTemplateResponse>(
      {
        method: "POST",
        path: `/template/warm`,
        body: params.body,
      },
      params,
    );
  }
}
